#!/usr/bin/env python3

from argparse import ArgumentParser
import asyncio
import logging
from s3watcher.server import S3Watcher


def main():
    aparser = ArgumentParser(
        description='Image S3 bucket watch service')
    aparser.add_argument('bucket', metavar='BUCKET',
                         help='S3 bucket name')
    aparser.add_argument('queue_url', metavar='QUEUE', nargs='?',
                         help='SQS queue URL')
    aparser.add_argument('--region', help='S3 region')
    aparser.add_argument('--session', action='store_true',
                         help='use DBus session bus')
    aparser.add_argument('--debug', action='store_true',
                         help='enable debug messages')
    args = aparser.parse_args()

    logging.basicConfig(level=logging.INFO)
    if args.debug:
        logger = logging.getLogger('s3watcher')
        logger.setLevel(logging.DEBUG)

    watcher = S3Watcher(args.bucket, args.queue_url, args.region)
    asyncio.run(watcher.run())


if __name__ == '__main__':
    main()
